# Datasets Info

This data sets consists of 3 different types of irises’ (Setosa, Versicolour, and Virginica) petal and sepal length, stored in a 150x4 numpy.ndarray

Features:

1) 'Sepal Length'

2) 'Sepal Width'

3) 'Petal Length'

4) 'Petal Width'

Output:

- setosa : 0

- versicolor : 1

- virginica : 2

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

2024-01-01 21:32:36.909657: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-01 21:32:37.411791: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-01 21:32:37.411886: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-01 21:32:37.475051: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-01 21:32:37.617038: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-01 21:32:37.619594: I tensorflow/core/platform/cpu_feature_guard.cc:1

Loading Iris Datasets

In [2]:
iris = load_iris()
X = iris.data
y = iris.target

Splitting the datasets into training and test sets

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


Creating a sequential model with 3 dense layers

In [4]:
model = Sequential([
   Dense(8, activation='relu', input_shape=(4,)),  # Input layer with 4 features
   Dense(16, activation='relu'),  # Hidden layer
   Dense(3, activation='softmax')  # Output layer with 3 classes
])

In [5]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Convert y_train and y_test to one-hot encoded vectors for categorical classification


In [6]:
y_train_cat = tf.keras.utils.to_categorical(y_train)
y_test_cat = tf.keras.utils.to_categorical(y_test)


Training the model


In [7]:
model.fit(X_train, y_train_cat, epochs=100, batch_size=10)

Epoch 1/100


12/12 [==============================] - 2s 7ms/step - loss: 1.3147 - accuracy: 0.3417
Epoch 2/100
12/12 [==============================] - 0s 3ms/step - loss: 1.0657 - accuracy: 0.5417
Epoch 3/100
12/12 [==============================] - 0s 4ms/step - loss: 0.8866 - accuracy: 0.6833
Epoch 4/100
12/12 [==============================] - 0s 5ms/step - loss: 0.7737 - accuracy: 0.8083
Epoch 5/100
12/12 [==============================] - 0s 6ms/step - loss: 0.7196 - accuracy: 0.8500
Epoch 6/100
12/12 [==============================] - 0s 5ms/step - loss: 0.6791 - accuracy: 0.7250
Epoch 7/100
12/12 [==============================] - 0s 5ms/step - loss: 0.6416 - accuracy: 0.7167
Epoch 8/100
12/12 [==============================] - 0s 7ms/step - loss: 0.6034 - accuracy: 0.7833
Epoch 9/100
12/12 [==============================] - 0s 7ms/step - loss: 0.5704 - accuracy: 0.8167
Epoch 10/100
12/12 [==============================] - 0s 5ms/step - loss: 0.5416 - accuracy: 0.8417
Epoch 11/100
12/12 [=

Evaluate the model on the testing set


In [8]:
loss, accuracy = model.evaluate(X_test, y_test_cat)

1/1 [==============================] - 1s 643ms/step - loss: 0.0865 - accuracy: 1.0000


In [9]:
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.0864974781870842
Test accuracy: 1.0


Let's predict on new data and evaluate it's performance

In [10]:
# model.predict() returns the probability for each class
y_pred_prob = model.predict(X_test)
print(y_pred_prob)

1/1 [==============================] - 0s 314ms/step
[[1.8442484e-03 9.6929741e-01 2.8858317e-02]
 [9.9779201e-01 2.2080548e-03 2.4984113e-08]
 [2.6506615e-09 6.1364647e-04 9.9938637e-01]
 [1.2237345e-03 9.1985220e-01 7.8924000e-02]
 [1.2472883e-03 9.7598332e-01 2.2769479e-02]
 [9.9548447e-01 4.5152665e-03 1.2621510e-07]
 [1.1465858e-02 9.8511994e-01 3.4141969e-03]
 [1.4210746e-05 1.3784046e-01 8.6214530e-01]
 [5.6605379e-04 6.6986942e-01 3.2956439e-01]
 [6.4015798e-03 9.8834670e-01 5.2515427e-03]
 [6.6756365e-05 3.3251971e-01 6.6741347e-01]
 [9.9468625e-01 5.3133322e-03 3.2194083e-07]
 [9.9775231e-01 2.2478099e-03 4.0808590e-08]
 [9.9517810e-01 4.8216097e-03 2.3570757e-07]
 [9.9793583e-01 2.0641172e-03 3.4524739e-08]
 [1.0637869e-03 9.5853293e-01 4.0403202e-02]
 [1.4428204e-07 4.8085586e-03 9.9519128e-01]
 [6.5060793e-03 9.8521650e-01 8.2774153e-03]
 [1.6726776e-03 9.2791885e-01 7.0408404e-02]
 [1.4864924e-07 4.2011617e-03 9.9579871e-01]
 [9.9455082e-01 5.4488778e-03 2.8896986e-07]
 [

In [11]:
#converting into labels for predicted probabilitic value
y_pred = tf.argmax(y_pred_prob, axis=1)
print(y_pred)

tf.Tensor([1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0], shape=(30,), dtype=int64)


In [13]:
#Actual label of target
y_test_actual = tf.argmax(y_test_cat, axis=1)
print(y_test_actual)

tf.Tensor([1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0], shape=(30,), dtype=int64)


In [14]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Calculate accuracy
accuracy = accuracy_score(y_test_actual, y_pred)
print("\nAccuracy:", accuracy)

# Display classification report
print("\nClassification Report:")
print(classification_report(y_test_actual, y_pred))

# Display confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test_actual, y_pred))


Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


<h4> In above specific confusion matrix:</h4>

- The model predicted Class 1 for 10 instances, and all of them actually belong to Class 1.

- The model predicted Class 2 for 9 instances, and all of them actually belong to Class 2.

- The model predicted Class 3 for 11 instances, and all of them actually belong to Class 3.